#ifndef SCUS_944_88_PART_008_H
#define SCUS_944_88_PART_008_H

bool FUN_80088b54(void);
dword LIBPRESS_OBJ_5F4(void);
int CdControl(u_char command, u_char *parameters, u_char *result);
int CdControlB(u_char command, u_char *parameters, u_char *result);
int CdControlF(u_char command, u_char *parameters);
int CdGetSector(void *memoryAddress, int sectorSize);
int CdInit(void);
int DecDCTinCallback(func *callbackFunction);
int DecDCTinSync(int syncMode);
int DecDCToutCallback(func *callbackFunction);
int DecDCToutSync(int syncMode);
int FUN_80085858(uint inputValue);
int FUN_80085890(int inputValue);
int FUN_800884e0(int padStructure);
int PadGetState(int portNumber);
int PadInfoAct(int portNumber, int actionIndex, int infoType);
int PadSetActAlign(int portNumber, uchar *actionData);
long StartCARD(void);
long StopCARD(void);
long _card_clear(long channelNumber);
long _card_info(long channelNumber);
long _card_read(long channelNumber, long blockNumber, uchar *buffer);
long _card_write(long channelNumber, long blockNumber, uchar *buffer);
undefined PDDIRRES_OBJ_2EC(int padStructure);
undefined PDENT2_OBJ_B8(void);
undefined4 BIOS_1_OBJ_0(void);
undefined4 BIOS_1_OBJ_64(byte *commandData);
undefined4 BIOS_1_OBJ_69C(void);
undefined4 BIOS_1_OBJ_6CC(void);
undefined4 BIOS_1_OBJ_91C(void);
undefined4 BIOS_1_OBJ_94C(void);
undefined4 CD_cw(byte command, byte *parameters, undefined *resultBuffer, int blockingMode);
undefined4 CD_ready(int readyMode, undefined *resultBuffer);
undefined4 CD_sync(int syncMode, undefined *resultBuffer);
undefined4 EVENT_OBJ_90(void);
undefined4 FUN_80087860(int padStructure);
undefined4 FUN_80088124(void);
undefined4 FUN_80088270(int padStructure);
undefined4 FUN_80088518(int *padStructure, int bufferSize);
undefined4 FUN_8008a088(undefined4 syncCallback);
undefined4 FUN_8008a0a8(undefined4 readyCallback);
undefined4 LIBPRESS_OBJ_4CC(void);
undefined4 LIBPRESS_OBJ_560(void);
undefined4 LIBPRESS_OBJ_60C(undefined4 timeoutMessage);
undefined4 PDCMD2_OBJ_138(int padStructure, byte *dataBuffer, int bufferIndex, int matchCount);
undefined4 PDCMD2_OBJ_A4(int padStructure);
undefined4 PDDIRRES_OBJ_25C(int padStructure);
undefined4 PDDIRRES_OBJ_5B4(int padStructure);
undefined4 PDDIRRES_OBJ_688(void);
undefined4 PDDIRRES_OBJ_A10(int padStructure);
undefined8 FUN_80086084(uint dividendLow, uint dividendHigh, uint divisorLow, uint divisorHigh);
void BIOS_1_OBJ_264(void);
void BIOS_1_OBJ_364(void);
void BIOS_1_OBJ_3B0(void);
void BIOS_1_OBJ_430(void);
void BIOS_1_OBJ_4B0(void);
void BIOS_1_OBJ_550(void);
void BIOS_1_OBJ_7B4(void);
void BIOS_1_OBJ_A7C(void);
void CD_getsector(void);
void DecDCTReset(int resetMode);
void DecDCTin(u_long *buffer, int decodeMode);
void DecDCTout(u_long *outputBuffer, int bufferSize);
void EVENT_OBJ_11C(void);
void EVENT_OBJ_80(void);
void EVENT_OBJ_BC(void);
void EVENT_OBJ_CC(void);
void EVENT_OBJ_F4(void);
void FUN_80085974(undefined4 param);
void FUN_80085990(void);
void FUN_800859fc(void);
void FUN_80085a98(void);
void FUN_80085ac8(int objectPointer, uint typeFlags);
void FUN_80085b3c(undefined4 *typeInfo, undefined4 typeName, undefined4 additionalInfo);
void FUN_80085b78(undefined4 *typeInfo, undefined4 typeName);
void FUN_80086060(int typeFlag);
void FUN_800870b8(void);
void FUN_80087b94(int padStructure);
void FUN_80088000(int startTime, int timeoutValue, ushort *timerValue, ushort *timerMode);
void FUN_800881b4(void);
void FUN_800881dc(int padStructure, undefined commandByte, undefined4 dataPointer, undefined statusByte);
void FUN_800881ec(int padStructure);
void FUN_80088a8c(int padStructure, undefined commandByte);
void FUN_80088aac(int padStructure);
void FUN_80088ac0(int padStructure, undefined commandByte);
void FUN_80088ae0(int padStructure, undefined commandByte);
void FUN_80088b00(int padStructure, undefined commandByte);
void FUN_80088b20(int padStructure);
void FUN_80088b34(undefined4 timeoutValue);
void InitCARD(long initValue);
void InitCARD2(void);
void LIBPRESS_OBJ_188(uint *bufferPointer, uint processFlags);
void LIBPRESS_OBJ_1B4(undefined4 *bufferPointer);
void LIBPRESS_OBJ_220(void);
void LIBPRESS_OBJ_268(void);
void LIBPRESS_OBJ_2C0(int resetMode);
void LIBPRESS_OBJ_394(void);
void LIBPRESS_OBJ_3A0(void);
void LIBPRESS_OBJ_3B0(dword *dataBuffer, uint dataSize);
void LIBPRESS_OBJ_440(dword outputBuffer, uint bufferSize);
void LIBPRESS_OBJ_550(void);
void LIBPRESS_OBJ_5E4(void);
void PDCMD2_OBJ_7C(int padStructure);
void PDDIRRES_OBJ_158(int errorCode);
void PDDIRRES_OBJ_1CC(void);
void PDDIRRES_OBJ_228(undefined4 statusValue, int errorCode);
void PDDIRRES_OBJ_24C(int padStructure);
void PDDIRRES_OBJ_2C0(void);
void PDDIRRES_OBJ_310(void);
void PDDIRRES_OBJ_318(int padStructure);
void PDDIRRES_OBJ_3EC(undefined4 statusValue, undefined4 dataValue, int actionFlag);
void PDDIRRES_OBJ_438(undefined4 statusValue, undefined4 dataValue, int actionFlag);
void PDDIRRES_OBJ_584(void);
void PDDIRRES_OBJ_6B4(void);
void PDDIRRES_OBJ_6C4(int padStructure);
void PDDIRRES_OBJ_7AC(undefined4 statusValue, uint expectedType);
void PDDIRRES_OBJ_8D4(void);
void PDDIRRES_OBJ_8E8(void);
void PDDIRRES_OBJ_910(void);
void PDDIRRES_OBJ_920(void);
void PDDIRRES_OBJ_A00(void);
void PDDIRRES_OBJ_F0(undefined4 *padStructure);
void PDENT2_OBJ_BC(void);
void PDENT4_OBJ_80(void);
void PDENT4_OBJ_8C(void);
void PDENT4_OBJ_98(void);
void PDENT4_OBJ_A4(void);
void PDENT4_OBJ_B0(void);
void PDENT4_OBJ_C0(void);
void PadInitDirect(uchar *port1Buffer, uchar *port2Buffer);
void PadSetAct(int portNumber, uchar *actionData, int actionType);
void PadStartCom(void);
void PadStopCom(void);
int S_016_OBJ_38C(void);
void StartCARD2(void);
void StopCARD2(void);
void _bu_init(void);
void _copy_memcard_patch(void);
void _dirFailAuto(int padStructure);
void _new_card(void);
void _padInitDirPort(void);
void _patch_card(void);
void _patch_card2(void);
void _patch_card_info(void);

#endif /* SCUS_944_88_PART_008_H */
